#! /bin/bash
# This only builds direct dependencies, as we don't care for indirect dependencies and wgpu-core in specific takes fucking ages to document. wgpu isn't much better
if [ $# -eq 0 ]
    then
        echo "Syntax: cargo_doc { open-docs | build-docs | perf }"
else
    if [ "build-docs" = "$1" ]
        then
            cargo tree --depth 1 -e normal --prefix none | cut -d' ' -f1 | xargs printf -- '-p %s\n' | xargs cargo doc --no-deps
            open "/home/supa/Code/Code Workspaces/games/terrace-game/target/doc/terrace_game/index.html"
    elif [ "open-docs" = "$1" ]
        then
            open "/home/supa/Code/Code Workspaces/games/terrace-game/target/doc/terrace_game/index.html"
    elif [ "perf" = "$1" ]
        then
            cargo build --release
            echo "Run the command 'sudo sudo perf record --call-graph dwarf ./target/release/terrace-game <mode>'"
            echo "Then, run the command 'sudo hotspot ./perf.data'"
    else
        echo "Unknown command: $1"
    fi
fi

